name = "tsconv"
compatibility_date = "2024-01-15"
pages_build_output_dir = "dist"
functions = "functions"

[env.production]
vars = { NODE_ENV = "production" }

[env.preview]
vars = { NODE_ENV = "development" }

# Custom domains will be configured in Cloudflare Dashboard
# This supports both tsconv.com and api.tsconv.com
